In [12]:
import numpy as np
import time

In [2]:
arr= np.array([1,2,3,4,5])

In [3]:
type(arr)

numpy.ndarray

In [5]:
np.shape(arr)

(5,)

In [7]:
# Proof that numpy stores element in less memory
import sys
list_data= list(range(1000))
numpy_data= np.array(list_data)

print("Python list size: ", sys.getsizeof(list_data) * len(list_data), " bytes")
print("Numpy array size: ", numpy_data.nbytes, " bytes")

Python list size:  8056000  bytes
Numpy array size:  8000  bytes


In [19]:
list1= [1,2,3,4,5]
arr= np.array(list1)

# Python List (loop-based)
start= time.time()
list_squares= [x**2 for x in list1]
end= time.time() 
print(end-start)

# Numpy (vectorized)
start= time.time()
numpy_squares= arr ** 2
end= time.time()
print(end-start)

print(list_squares)
print(numpy_squares)

0.00019240379333496094
0.00012969970703125
[1, 4, 9, 16, 25]
[ 1  4  9 16 25]


In [20]:
# array of zeros
arr1= np.zeros((3,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
# array of ones
arr2= np.ones((2,5))
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
# arry filled with a specific number
arr3= np.full((2,2), 7)
arr3

array([[7, 7],
       [7, 7]])

In [31]:
# Identity matrix
arr4= np.eye(4)
arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
# range of numbers in an array
arr5= np.arange(10,100,2)
arr5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [36]:
# Evenly spaced array
arr5= np.linspace(1,5,5)
arr5

array([1., 2., 3., 4., 5.])

In [39]:
arr= np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,13]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]])

In [41]:
arr.shape

(4, 3)

In [46]:
# total elements in the array
arr.size

12

In [45]:
# Dimensions of the arrays
arr.ndim

2

In [44]:
arr.dtype

dtype('int64')

In [47]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 13]])

In [48]:
# To explicitly change datatype
arr= np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,13]], dtype= 'float32')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 13.]], dtype=float32)

In [49]:
arr.dtype

dtype('float32')

In [55]:
# Alternate way
arr= np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,13]])
n= arr.astype('float64')


n.dtype

dtype('float64')

In [57]:
arr= np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,13]])
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13])