In [1]:
import numpy as np

In [2]:
arr= np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,13]])
flat= arr.flatten()

In [3]:
flat[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13])

In [4]:
flat[:13]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13])

In [5]:
flat[3:7]

array([4, 5, 6, 7])

In [6]:
b= flat[3:7] # It will create a VIEW
b

array([4, 5, 6, 7])

In [7]:
b[1]= 30000

In [8]:
flat

array([    1,     2,     3,     4, 30000,     6,     7,     8,     9,
          10,    11,    13])

In [9]:
c= flat[3:7].copy() # This will create a copy 
c[1]= 9899999

In [10]:
flat

array([    1,     2,     3,     4, 30000,     6,     7,     8,     9,
          10,    11,    13])

In [11]:
# fancy indexing -> select multiple elements
arr= np.array([12,3,45,65,4,66,32,47,90,87])
arr[[1,2,3]]

array([ 3, 45, 65])

In [12]:
# Boolean Masking for filtering data
arr= np.array([12,3,45,65,4,66,32,47,90,87])
mask = arr > 34
arr[mask]

array([45, 65, 66, 47, 90, 87])

## EXERCISE

In [14]:
# Create a 3x3 matrix filled wth random numbers
arr= np.array([[1,2,3], [4,5,6], [7,8,9]])
arr.shape

(3, 3)

In [19]:
# convert array of floats into integers
arr= np.array([1.1,1.2,1.3, 3.4, 6.7, 9.6])
new_arr= arr.astype('int32')
new_arr

array([1, 1, 1, 3, 6, 9], dtype=int32)

In [20]:
new_arr.dtype

dtype('int32')

In [21]:
arr.dtype

dtype('float64')

In [24]:
# Reshape a 1 D array of size 9
arr= np.array([1,2,3,4,5,6,7,8,9])
new_arr= arr.reshape(3,3)

In [25]:
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
# Use fancy indexing to extract even numbers from [1,2,3,4,5,6]
arr= np.array([1,2,3,4,5,6])
arr[[1,3,5]]

array([2, 4, 6])

In [30]:
# Use boolean masking to find elements greater than 50
arr= np.arange(10,100,20)
print(arr)
arr[arr>50]

[10 30 50 70 90]


array([70, 90])